name: Jekyll Deploy

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    
    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: 2.5.7
        bundler-cache: true # runs 'bundle install' and caches installed gems automatically
    - run: jekyll build --future
    
    - name: Build & Deploy to GitHub Pages
      uses: DavidS/jekyll-deploy@main
      env:
        JEKYLL_ENV: production
        GH_PAGES_TOKEN: ${{ secrets.GH_PAGES_TOKEN }}
      
